### ISSUE TITLE
nimtwirp_build.nim(40, 11) Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error

### ISSUE THREAD

**Issue by timotheecour** [oswjk/nimtwirp#2]
nimble install
  Verifying dependencies for nimtwirp@0.1.0
   Warning: No nimblemeta.json file found in /Users/timothee/.nimble/pkgs/choosenim-0.3.2
      Info: Dependency on nimpb@any version already satisfied
  Verifying dependencies for nimpb@0.2.0
      Info: Dependency on nimpb_protoc@any version already satisfied
  Verifying dependencies for nimpb_protoc@0.1.0
 Installing nimtwirp@0.1.0
   Building nimtwirp/nimtwirp/nimtwirp_build using c backend
       Tip: 138 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: nimtwirp
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/Users/timothee/.nimble//bin/nim" c --noBabelPath -d:release --path:"/Users/timothee/.nimble/pkgs/nimpb-0.2.0"  --path:"/Users/timothee/.nimble/pkgs/nimpb_protoc-0.1.0"  -o:"/Users/timothee/git_clone/nim/nimtwirp/nimtwirp/nimtwirp_build" "/Users/timothee/git_clone/nim/nimtwirp/nimtwirp/nimtwirp_build.nim"
        ... Output: Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
        ... Hint: used config file '/Users/timothee/.config/nim/nim.cfg' [Conf]
        ... Hint: used config file '/Users/timothee/.config/nim/config.nims' [Conf]
        ... /Users/timothee/.config/nim/timn/config.nims D20180822T214914
        ... /Users/timothee/git_clone/nim/nimtwirp/nimtwirp/nimtwirp_build.nim(5, 8) Warning: Use the 'parseopt' module instead; parseopt2 is deprecated [Deprecated]
        ...   import parseopt2
        ...          ^
        ... /Users/timothee/git_clone/nim/nimtwirp/nimtwirp/nimtwirp_build.nim(20, 1) template/generic instantiation from here
        ... /Users/timothee/git_clone/nim/nimtwirp/nimtwirp/nimtwirp_build.nim(40, 11) Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error
        ...   if outdir == nil:

**Comment by oskaritimperi** [comment]
Should be fixed.
